<a href="https://colab.research.google.com/github/OlegV12/Torch/blob/Lesson_1/HW_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import random 

In [ ]:
# 1. Создайте случайный FloatTensor размера 3x4x5
a = torch.rand(3, 4, 5)

In [ ]:
print(a)
print(a.type())

tensor([[[0.3992, 0.2727, 0.0166, 0.9941, 0.4015],
         [0.6634, 0.7044, 0.6727, 0.4089, 0.1513],
         [0.9545, 0.5833, 0.0740, 0.9268, 0.6763],
         [0.7809, 0.6702, 0.4909, 0.8576, 0.6878]],

        [[0.8757, 0.6399, 0.2518, 0.7236, 0.8118],
         [0.6138, 0.8829, 0.4717, 0.4356, 0.8682],
         [0.3711, 0.6121, 0.1832, 0.3632, 0.0253],
         [0.7043, 0.1042, 0.4615, 0.1322, 0.2577]],

        [[0.7436, 0.4750, 0.3196, 0.2182, 0.3502],
         [0.5274, 0.3406, 0.4774, 0.3974, 0.0637],
         [0.0831, 0.7042, 0.9833, 0.2699, 0.2002],
         [0.5989, 0.1113, 0.0669, 0.7013, 0.1510]]])
torch.FloatTensor


In [ ]:
# 2. Выведите его форму (shape)
a.shape

torch.Size([3, 4, 5])

In [ ]:
# 3. Приведите его к форме 6х10
a = a.reshape(6, 10)
print(a)
a.size()

tensor([[0.3992, 0.2727, 0.0166, 0.9941, 0.4015, 0.6634, 0.7044, 0.6727, 0.4089,
         0.1513],
        [0.9545, 0.5833, 0.0740, 0.9268, 0.6763, 0.7809, 0.6702, 0.4909, 0.8576,
         0.6878],
        [0.8757, 0.6399, 0.2518, 0.7236, 0.8118, 0.6138, 0.8829, 0.4717, 0.4356,
         0.8682],
        [0.3711, 0.6121, 0.1832, 0.3632, 0.0253, 0.7043, 0.1042, 0.4615, 0.1322,
         0.2577],
        [0.7436, 0.4750, 0.3196, 0.2182, 0.3502, 0.5274, 0.3406, 0.4774, 0.3974,
         0.0637],
        [0.0831, 0.7042, 0.9833, 0.2699, 0.2002, 0.5989, 0.1113, 0.0669, 0.7013,
         0.1510]])


torch.Size([6, 10])

In [ ]:
# 4. Создайте случайный IntTensor размера 10
b = torch.randint(0, 9, size=(10,))
b

tensor([3, 6, 3, 0, 5, 8, 7, 3, 2, 2])

In [ ]:
# 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
d = a * b
d

tensor([[1.1975, 1.6364, 0.0498, 0.0000, 2.0073, 5.3070, 4.9308, 2.0181, 0.8178,
         0.3025],
        [2.8636, 3.4998, 0.2219, 0.0000, 3.3816, 6.2475, 4.6912, 1.4726, 1.7153,
         1.3756],
        [2.6271, 3.8393, 0.7555, 0.0000, 4.0588, 4.9104, 6.1804, 1.4152, 0.8712,
         1.7364],
        [1.1133, 3.6724, 0.5496, 0.0000, 0.1265, 5.6346, 0.7293, 1.3845, 0.2645,
         0.5155],
        [2.2309, 2.8503, 0.9589, 0.0000, 1.7509, 4.2194, 2.3844, 1.4321, 0.7948,
         0.1274],
        [0.2492, 4.2251, 2.9498, 0.0000, 1.0010, 4.7911, 0.7789, 0.2007, 1.4026,
         0.3021]])

In [ ]:
# 6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
# Подсказка: .dot может не подойти
d @ d.T

tensor([[ 65.4544,  77.0336,  78.2415,  44.2894,  48.6263,  40.2790],
        [ 77.0336,  99.9757, 100.4912,  58.4155,  63.6914,  56.2433],
        [ 78.2415, 100.4912, 106.7729,  53.2129,  63.0304,  53.5375],
        [ 44.2894,  58.4155,  53.2129,  49.5774,  41.4719,  45.9101],
        [ 48.6263,  63.6914,  63.0304,  41.4719,  43.2736,  40.6932],
        [ 40.2790,  56.2433,  53.5375,  45.9101,  40.6932,  53.2766]])

In [ ]:
# 7. Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor((1, 0.5, 2), requires_grad=True)

y = x**3

y.backward(x)
x.grad

tensor([ 3.0000,  0.3750, 24.0000])

In [ ]:
# 8. Создайте единичный тензор размера 5x6
ones = torch.ones((5, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [ ]:
# 9. Переведите его в формат numpy
ones = np.array(ones)
ones

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)